services:
  dictionary-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dictionary-backend:latest
    container_name: dictionary
    restart: always
    ports:
      - '3000:3000'
