@startuml dictionary
!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>

table( invite_tokens ) {
  * primary_key( id ): INT
  ---
  {field} * token: VARCHAR(36) <<UNIQUE>>
  * time_create: DATETIME
  time_expiration: DATETIME
}

table( users ) {
  id, invite_token_id, name, email, password, confirm_code, reset_password_token, time_create, time_edit
}

table( languages ) {
  id, user_id, name, country, flag, time_create, time_edit
}

table( words ) {
  id, language_id, level_id, formality, complexity, word, word_v2, word_v3, translation, description_target, description_local, transcription_strict, transcription_phonetic, is_favorite, time_create, time_edit
}

table( synonyms ) {
  word_id, synonym_id, description, time_create, time_edit
}

table( antonyms ) {
  word_id, antonym_id, description, time_create, time_edit
}

table( tags ) {
  id, language_id, name, title, color
}

table( words_tags ) {
  word_id, tag_id
}

table( examples ) {
  id, word_id, example, translation, description, time_create, time_edit
}

table( translations ) {
  id, word_id, part_of_speech_id, translation, description, weight, time_create, time_edit
}

table( translations_examples ) {
  translation_id, example_id
}

table( levels ) {
  id, language_id, name, title
}

table( parts_of_speech ) {
  id, language_id, name, title
}

table( words_progress ) {
  id, word_id, interval, success_count, failure_count, time_last_review
}

@enduml