-- AlterTable
ALTER TABLE "antonyms" ALTER COLUMN "time_create" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "time_edit" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "examples" ALTER COLUMN "time_create" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "time_edit" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "invite_tokens" ALTER COLUMN "time_create" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "time_expiration" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "languages" ALTER COLUMN "time_create" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "time_edit" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "synonyms" ALTER COLUMN "time_create" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "time_edit" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "time_create" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "time_edit" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "words" ALTER COLUMN "time_create" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "time_edit" SET DATA TYPE TIMESTAMPTZ(6);
