export const Constants = {
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 50,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
  },
  WORD: {
    MIN_COMPLEXITY: 1,
    MAX_COMPLEXITY: 5,
    MIN_FORMALITY: 1,
    MAX_FORMALITY: 5,
  },
  BATCH: {
    SIZE: Number(process.env.BATCH_SIZE) || 1000,
  },
}
